services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ROOT
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - /home/duylam/Documents/Study-Hust/20251/Chat-App/minio/data:/data
    command: server /data --console-address ":9001"
